description: "專案層級映射: Angular 20 + NgRx Signals + Firebase"
version: "1.0.0"

# Domain 層: 純 TS 模型與規則
domain:
  - path: "src/app/domain/account"
  - path: "src/app/domain/context"
  - path: "src/app/domain/document"
  - path: "src/app/domain/member"
  - path: "src/app/domain/module"
  - path: "src/app/domain/notification"
  - path: "src/app/domain/organization"
  - path: "src/app/domain/partner"
  - path: "src/app/domain/repositories"
  - path: "src/app/domain/shared"
  - path: "src/app/domain/tasks"
  - path: "src/app/domain/team"
  - path: "src/app/domain/workspace"

# Application 層: signalStore + rxMethod
application:
  - path: "src/app/application/account"
  - path: "src/app/application/auth"
  - path: "src/app/application/context"
  - path: "src/app/application/document"
  - path: "src/app/application/member"
  - path: "src/app/application/module"
  - path: "src/app/application/notification"
  - path: "src/app/application/organization"
  - path: "src/app/application/partner"
  - path: "src/app/application/quiz"
  - path: "src/app/application/services"
  - path: "src/app/application/tasks"
  - path: "src/app/application/team"
  - path: "src/app/application/tokens"
  - path: "src/app/application/ui"
  - path: "src/app/application/workspace"
  - path: "src/app/application/index.ts"

# Infrastructure 層: 封裝 Firebase / API
infrastructure:
  - path: "src/app/infrastructure/account"
  - path: "src/app/infrastructure/auth"
  - path: "src/app/infrastructure/document"
  - path: "src/app/infrastructure/member"
  - path: "src/app/infrastructure/module"
  - path: "src/app/infrastructure/notification"
  - path: "src/app/infrastructure/organization"
  - path: "src/app/infrastructure/partner"
  - path: "src/app/infrastructure/tasks"
  - path: "src/app/infrastructure/team"
  - path: "src/app/infrastructure/workspace"

# Interface / Presentation 層: 組件 / page / guard
interface:
  - path: "src/app/presentation/features"
  - path: "src/app/presentation/shared"
  - path: "src/app/presentation/app.component.ts"
  - path: "src/app/presentation/app.routes.ts"

# Shared / 公共
shared:
  - path: "src/app/shared/constants"
  - path: "src/app/shared/models"
  - path: "src/app/shared/services"

# 備註
notes:
  - "所有 Domain 模型僅用於 Application 層，不可被 Interface / Service 直接 import"
  - "所有 store 都使用 signalStore + rxMethod"
  - "所有 template 使用 @if/@for/@switch"
  - "禁止 @ngrx/store / effects / entity"
  - "異步操作必須使用 rxMethod + tapResponse"
